Add order functionality
AdamMudrak/online_book_shop pull request #11
Opened 2024-06-24 18:24 UTC by AdamMudrak

2024-06-25 07:42 UTC, Elena-Bruyako requested changes
Let's improve your solution!

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/dto/order/request/AddressDto.java
> +public record AddressDto(
```suggestion
public record CreateOrderRequestDto(
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/dto/order/request/AddressDto.java
> +        @NotNull
```suggestion
        @NotBlank
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/dto/order/request/StatusRequestDto.java
> +public record StatusRequestDto(
```suggestion
public record UpdateOrderDto(
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/dto/order/response/OrderDto.java
> +    @Enumerated(EnumType.STRING)
Do we need this annotation here in Response?

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/dto/order/response/OrderDto.java
> +    public enum StatusDto {
You already have Status enum in Entity

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/entities/Order.java
> +    @Column(name = "order_time", nullable = false)
```suggestion
    @Column(nullable = false)
```
Hibernate automatically create name with snake_case

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/entities/Order.java
> +    @Column(name = "shipping_address", nullable = false)
```suggestion
    @Column(nullable = false)
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/entities/Order.java
> +@Table(name = "orders")
```suggestion
@Table(name = "orders")
@SQLRestriction(value = "is_deleted=false")
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/repositories/order/OrderRepository.java
> +    List<Order> findAllByUserId(Long userId);
```suggestion
    List<Order> findAllByUserId(Long userId, Pageable pageable);
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +            throw new EmptyCartException(
```suggestion
            throw new OrderProcessingException(
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/dto/order/request/StatusRequestDto.java
> +        Integer status) {
```suggestion
        String status) {
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +        Optional<Order> optionalOrder = orderRepository.findById(orderId);
```suggestion
        Order order = orderRepository.findById(orderId)
                .map(o -> {
                    o.setStatus(Status.valueOf(orderDto.status()));
                    return o;
                })
                .orElseThrow(() -> new EntityNotFoundException(
                        String.format("Order with id: %d not found", orderId)
                ));
        return orderMapper.orderToOrderDto(order);
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +        Optional<Order> optionalOrder = orderRepository.findById(orderId);
```suggestion
        Order order = orderRepository.findByIdAndUserId(orderId, userId)
                .orElseThrow(() -> new EntityNotFoundException(
                        String.format("Order with id: %d not found for user: %d", orderId, userId)
                ));
        return orderItemMapper.toOrderItemDtoList(order.getOrderItems());
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +        Optional<Order> optionalOrder = orderRepository.findById(orderId);
```suggestion
        OrderItem item = itemRepository.findByIdAndOrderIdAndUserId(orderItemId, orderId, userId)
                .orElseThrow(() -> new EntityNotFoundException(
                        String.format("Order item: %d not found in order: %d for user: %d",
                                orderItemId, orderId, userId)
                ));
        return orderItemMapper.toOrderItemDto(item);
```

2024-06-25 07:42 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +        if (addressDto.shippingAddress().isBlank()) {
Could be address blank, if you have constraint in DTO?

2024-06-25 10:36 UTC, AdamMudrak commented on src/main/java/com/example/onlinebookshop/dto/order/response/OrderDto.java
> +    public enum StatusDto {
Didn't know I am allowed to use it

2024-06-25 14:13 UTC, AdamMudrak commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +        if (addressDto.shippingAddress().isBlank()) {
It can :) Check you DMs in Mate

2024-06-27 07:28 UTC, Elena-Bruyako requested changes
Left some comments

2024-06-27 07:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +        if (createOrderDto.shippingAddress().isBlank()) {
You have NotBlank validation, so I think this check is redundant. 
Also, remove the exception

2024-06-27 07:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +        Optional<Order> optionalOrder = orderRepository.findById(orderId);
Can we use the same approach like in below method?
```suggestion
        Order order = orderRepository.findById(orderId).orElseThrow(() -> 
        return orderItemMapper.toOrderItemDtoList(order.getOrderItems());
```

2024-06-27 07:28 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +        Optional<Order> optionalOrder = orderRepository.findById(orderId);
Can we use the same approach as in findOrderItemsByOrderIdAndItemId ?

2024-06-27 12:42 UTC, okuzan requested changes
remove redundancy in naming:
`constants / dtoconstants` to `constants / dto`

2024-06-27 12:42 UTC, okuzan commented on src/main/java/com/example/onlinebookshop/controller/OrderController.java
> +        } else {
you don't need else after return

2024-06-27 12:42 UTC, okuzan commented on src/main/java/com/example/onlinebookshop/dto/order/response/OrderDto.java
> +
```suggestion
```

2024-06-27 12:42 UTC, okuzan commented on src/main/java/com/example/onlinebookshop/dto/order/response/OrderDto.java
> +@Setter
It's ok to use @ Data for DTO

2024-06-27 12:42 UTC, okuzan commented on src/main/java/com/example/onlinebookshop/entities/Order.java
> +@SQLRestriction(value = "is_deleted=false")
```suggestion
@SQLRestriction(value = "is_deleted = FALSE")
```
uppercase SQL keywords

2024-06-27 12:42 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/20-populate-order-items-table.yaml
```suggestion
      file: db/changelog/changes/20-populate-order-items-table.yaml

```

2024-06-27 12:42 UTC, okuzan commented on src/main/java/com/example/onlinebookshop/services/impl/OrderServiceImpl.java
> +                .map(o -> {
don't use one-letter naming even in stream chains

2024-06-28 06:38 UTC, Elena-Bruyako approved these changes
Good job!

2024-06-28 12:01 UTC, merged