Hw jv add tests for book and category
AdamMudrak/online_book_shop pull request #14
Opened 2024-08-02 20:53 UTC by AdamMudrak

2024-08-06 18:33 UTC, AdamMudrak commented
![image](https://github.com/user-attachments/assets/8127ce96-1a7e-418f-88a4-0323f1b30aaa) - after BookContollerTest
![image](https://github.com/user-attachments/assets/288aa054-8c42-4d8b-8db2-9da80032c28e) - after CategoryControllerTest
![image](https://github.com/user-attachments/assets/06d50567-e15f-41ad-8211-3c70da79015c) - after BookServiceTest
![image](https://github.com/user-attachments/assets/548132f0-77d4-4e83-a5c2-75323c2f63ab) - after CategoryServiceTest

2024-08-08 10:05 UTC, MentorMateAcademy requested changes

2024-08-08 10:05 UTC, MentorMateAcademy commented on src/main/java/com/example/onlinebookshop/constants/dtos/CategoryDtoConstants.java
> +package com.example.onlinebookshop.constants.dtos;
```suggestion
package com.example.onlinebookshop.constants.dto;
```

2024-08-08 10:05 UTC, MentorMateAcademy commented on src/main/java/com/example/onlinebookshop/constants/dtos/CategoryDtoConstants.java
> +package com.example.onlinebookshop.constants.dtos;
don`t change for DTOs

2024-08-08 10:05 UTC, MentorMateAcademy commented on src/test/java/com/example/onlinebookshop/BookCategoryConstants.java
> +public class BookCategoryConstants {
add utilityClass anno from lombok

2024-08-09 13:56 UTC, okuzan approved these changes

2024-08-12 16:13 UTC, merged