Hw global exception validation
AdamMudrak/online_book_shop pull request #4
Opened 2024-04-22 16:00 UTC by AdamMudrak

2024-04-23 06:54 UTC, Elena-Bruyako requested changes
Well done. Let's improve your solution!

2024-04-23 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/dto/BookSearchParametersDto.java
> +        @Min(0) @Digits(integer = 17, fraction = 2)
Better @Positive instead of Min

2024-04-23 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/dto/CreateBookRequestDto.java
> +    @Min(value = 0)
@Positive

2024-04-23 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/exceptions/CustomGlobalExceptionHandler.java
> +                HttpStatus.BAD_REQUEST,
For EntityNotFoundException is better NOT_FOUND status. 
Use static import 
```suggestion
                BAD_REQUEST,
```

2024-04-23 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/exceptions/CustomGlobalExceptionHandler.java
> +    private String getErrorMessage(ObjectError e) {
private should be placed after public and protected methods

2024-04-23 06:54 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/BookServiceImpl.java
> +    private void validateId(Long id) {
Just add @Positive Long id in endpoint updateBook and @Validated over the BookController
remove this method

2024-04-24 11:10 UTC, Rommelua approved these changes

2024-04-24 15:22 UTC, merged