Hw second step in security
AdamMudrak/online_book_shop pull request #7
Opened 2024-05-08 20:31 UTC by AdamMudrak

2024-05-08 20:38 UTC, AdamMudrak commented
I'd like to point out that I am pull requesting more not because I prepared a good solution, but because I don't really understand if I am doing everything correctly. Specifically,
**1. In the users_roles table ensure columns together form a composite key**  - I am not sure if this is done correctly:
**2. Think about how we should add columns like is_deleted. Should we add them directly to existing scripts or there is another better way?
3. Think if is it ok to hardcode identifiers in the Liquibase scripts? What is the difference between value and valueComputed in the YML scripts?** - Where can I find example of this? I've tried, not really successfully

+ I am not sure that getting 403 forbidden is a good thing...

2024-05-09 06:04 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/security/SecurityConfig.java
> +                                .requestMatchers("/auth/**", "/error")
```suggestion
                                .requestMatchers(
                                        antMatcher("/api/auth/**"),
                                        antMatcher("/swagger-ui/**"),
                                        antMatcher("/v3/api-docs/**"),
                                        antMatcher("/errors")
                                )
```

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/UserDetailsServiceImpl.java
> +    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String email) {
```

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/UserDetailsServiceImpl.java
> +        return userRepository.findByEmail(email).orElseThrow(() -> new UsernameNotFoundException(
```suggestion
        return userRepository.findByEmail(email).orElseThrow(() -> new EntityNotFoundException(
```

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +              - column:
Don't need to add roles here, as you create table users-roles

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                constraints:
```suggestion
                constraints:
                    nullable: true
                    foreignKeyName: fk_user_id
                    references: users(id)
```

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/04-create-users-roles-table.yaml
> +                constraints:
the same

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/README.txt
> +The passwords are:
Readme file shouldn't be here

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/UserDetailsServiceImpl.java
> +package com.example.onlinebookshop.services.impl;
```suggestion
package com.example.onlinebookshop.security;
```
replace to another package

2024-05-09 06:04 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/security/SecurityConfig.java
> +package com.example.onlinebookshop.security;
```suggestion
package com.example.onlinebookshop.config;
```
replace to another package

2024-05-09 10:54 UTC, kerrrusha approved these changes

2024-05-11 12:32 UTC, merged