Hw last step in security
AdamMudrak/online_book_shop pull request #8
Opened 2024-05-11 23:56 UTC by AdamMudrak

Again, I'm sending HW because I don't understand what I am doing wrong - need a tip. In swagger only register and login works - it gives the token, but all the other methods just throw 401. But even login and register method show this form:
![image](https://github.com/AdamMudrak/online_book_shop/assets/113807446/95922347-5189-4c88-810f-b3bf3e0d63a2)
In postman nothing works at all.

2024-05-12 05:48 UTC, Elena-Bruyako requested changes
Good job! 
Let's fix some comments and if you still have the problem with auth via postman or swagger text in chat and we take a look

2024-05-12 05:48 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```
you can use spring constant

2024-05-12 05:48 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Create constant for "Bearer "

2024-05-12 05:48 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/UserServiceImpl.java
> +        requestDto.setPassword(passwordEncoder.encode(requestDto.getPassword()));
Let create User first
```suggestion
        User user = userMapper.toUser(requestDto);
        user.setRoles( // set USER role
        user.setPassword(passwordEncoder.encode(request.password()));
        userRepository.save(user);
        return userMapper.toUserResponseDto(user);
```

2024-05-12 05:48 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/UserServiceImpl.java
> +    public UserLoginResponseDto authenticate(UserLoginRequestDto requestDto) {
Let's create AuthenticationService in security package and replace authentication logic there
```suggestion
    public UserLoginResponseDto authenticate(UserLoginRequestDto requestDto) {
        final Authentication authentication = manager
                .authenticate(
                        new UsernamePasswordAuthenticationToken(
                                requestDto.email(), requestDto.password()));
        String token = jwtUtil.generateToken(authentication.getName());
        return new UserLoginResponseDto(token);
    }
```

Also, add bean to SecurityConfig
```
@Bean
    public AuthenticationManager authenticationManager(
            AuthenticationConfiguration authenticationConfiguration) throws Exception {
        return authenticationConfiguration.getAuthenticationManager();
    }
```

2024-05-13 18:39 UTC, AdamMudrak commented on src/main/java/com/example/onlinebookshop/config/SecurityConfig.java
>                  .httpBasic(withDefaults())
I don't think we need line 52 at all, because according to my understanding, it will not be used at all

2024-05-14 06:48 UTC, Elena-Bruyako requested changes
See comments

2024-05-14 06:48 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/config/SecurityConfig.java
>                  .httpBasic(withDefaults())
Correct, you can remove it

2024-05-14 06:48 UTC, Elena-Bruyako commented on src/main/java/com/example/onlinebookshop/services/impl/UserServiceImpl.java
> +        Set<Role> roles = user.getRoles();
Or simplified
`user.setRoles(Set.of(userRole));`

2024-05-14 20:06 UTC, sarakhmen approved these changes
Good job :)

2024-05-14 20:25 UTC, merged